// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/models": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all tracker models currently supported",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Get list of tracker models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Model"
                            }
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Add support for new model, by specifing which SMS messages should be sent when the tracker model is provisioned. The tracker model, must support GT06 or JT808, to work.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Create model",
                "parameters": [
                    {
                        "description": "Register model payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateModelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "400": {
                        "description": "failed to parse OR API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR You don't have access to this feature",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "500": {
                        "description": "failed",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/models/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Get model by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Model"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "404": {
                        "description": "Model was not found",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove support for tracker model",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Delete model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR You don't have access to this feature",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "500": {
                        "description": "failed",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/trackers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "If the user is a admin, it will respond with a list of all trackers in the system, and if the user is a regular user, it will return all trackers owned by the user,",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trackers"
                ],
                "summary": "Get list of trackers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TrackerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Register tracking by supplying all properties of a tracker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trackers"
                ],
                "summary": "Register tracker",
                "parameters": [
                    {
                        "description": "Register tracker payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterTrackerReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "400": {
                        "description": "failed to parse OR API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "403": {
                        "description": "This action requires admin permissions",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "409": {
                        "description": "Tracker with identical id or name already exists",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "500": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/trackers/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trackers"
                ],
                "summary": "Get tracker by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrackerID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TrackerResponse"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR not allowed to access tracker",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "403": {
                        "description": "You don't have a tracker registered with the specified id",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "404": {
                        "description": "Tracker not found",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trackers"
                ],
                "summary": "Deregister tracker by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrackerID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR not allowed to access tracker",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "500": {
                        "description": "failed",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/trackers/{id}/command": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send upstream command to specified tracker, and get tracker response. The request will fail if the tracker is not currently connected. Additionally the request may timeout, if the tracker is connected but does not response. This can happen if the tracker has entered sleep mode without first closing the TCP connection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commands"
                ],
                "summary": "Send command",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrackerID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Command",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CommandReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "RESPONSE",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "400": {
                        "description": "failed to parse OR API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR not allowed to access tracker",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "503": {
                        "description": "The tracker is not connected",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/trackers/{id}/location": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the latest location data event reported by specified tracker",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Get tracker location",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrackerID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LocationResponse"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR not allowed to access tracker",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "404": {
                        "description": "No location entry found",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/trackers/{id}/locations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a array with all location data events reported by specified tracker",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Location"
                ],
                "summary": "Get tracker locations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrackerID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/api.LocationResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key OR not allowed to access tracker",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "404": {
                        "description": "No location entry found",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        },
        "/whoami": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fetch the user/organization name associated with the used API key. This can be used to detect if a api-key is valid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Whoami",
                "responses": {
                    "200": {
                        "description": "NAME OF USER/ORGANISATION",
                        "schema": {
                            "$ref": "#/definitions/api.NameRes"
                        }
                    },
                    "400": {
                        "description": "API key required",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    },
                    "401": {
                        "description": "Invalid API key",
                        "schema": {
                            "$ref": "#/definitions/api.StringResultRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CommandReq": {
            "type": "object",
            "required": [
                "command"
            ],
            "properties": {
                "command": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "api.CreateModelReq": {
            "type": "object",
            "required": [
                "init_commands",
                "name",
                "success_keywords"
            ],
            "properties": {
                "init_commands": {
                    "type": "string",
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 2
                },
                "success_keywords": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "api.LocationResponse": {
            "type": "object",
            "properties": {
                "heading": {
                    "type": "integer"
                },
                "lat": {
                    "type": "integer"
                },
                "lon": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.NameRes": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.RegisterTrackerReq": {
            "type": "object",
            "required": [
                "enabled",
                "id",
                "model",
                "name",
                "phoneNumber"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 12
                },
                "model": {
                    "type": "string",
                    "minLength": 2
                },
                "name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                },
                "owner": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "api.StringResultRes": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "api.TrackerResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "heading": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "lastConnected": {
                    "type": "string"
                },
                "lat": {
                    "type": "integer"
                },
                "lon": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "speed": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.Model": {
            "type": "object",
            "properties": {
                "init_commands": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "success_keywords": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.banjo.dev:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Trackerr",
	Description:      "API for Trackerr service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
